## **Basics of Numpy Arrays**

### Types of Array

1. One Dimensional Array

In [1]:
import numpy as np

a = [1, 2, 3, 4, 5]

arr = np.array(a)

print("List in python:", a)
print("Array in numpy:", arr)

List in python: [1, 2, 3, 4, 5]
Array in numpy: [1 2 3 4 5]


2. Multi-Dimensional Array

In [2]:
import numpy as np

list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]
list_3 = [11, 12, 13, 14, 15]

arr = np.array([list_1, list_2, list_3])

print('Numpy multi dimensional array:\n', arr)

Numpy multi dimensional array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Parameters of a Numpy Array

1. Axis  
Axis 0 = one dimensional  
Axis 1 = two dimensional  
Axis 2 = three dimensional

2. Shape

In [3]:
import numpy as np

sample_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [10, 11, 12]])

print('Shape of the array:', sample_array.shape)

Shape of the array: (4, 3)


3. Rank  
One-dimensional array has rank 1  
Two-dimensional array has rank 2

4. Date type objects (dtype)

In [4]:
import numpy as np

sample_array_1 = np.array([[1, 2, 3]])
sample_array_2 = np.array([[4.0, 5.0, 6.0]])

print('Data type of sample_array_1:', sample_array_1.dtype)
print('Data type of sample_array_2:', sample_array_2.dtype)

Data type of sample_array_1: int64
Data type of sample_array_2: float64


### Different Ways of Creating Numpy Array

1. numpy.array()

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print('Array:', arr)

Array: [1 2 3 4 5]


2. numpy.fromiter()

In [6]:
import numpy as np

var = "Hello, World!"
arr = np.fromiter(var, dtype='U2')

print('fromiter() array:', arr)

fromiter() array: ['H' 'e' 'l' 'l' 'o' ',' ' ' 'W' 'o' 'r' 'l' 'd' '!']


3. numpy.arange()

In [7]:
import numpy as np

np.arange(1, 20, 2, dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

4. numpy.linspace()

In [8]:
import numpy as np

np.linspace(3.5, 10, 3, dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

5. numpy.empty()

In [9]:
import numpy as np

np.empty([4, 3], dtype = np.int32, order = 'f')

array([[-1887892323,  1717711458,  1667447088],
       [          5,  1697670758,   811820085],
       [          0,   926364002,          54],
       [          0,   828651574,       32718]], dtype=int32)

6. numpy.ones()

In [12]:
import numpy as np

np.ones([4, 3], dtype = np.int32, order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

7. numpy.zeros()

In [14]:
import numpy as np

np.zeros([4, 3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

## **Different Ways to Create Numpy Arrays in Python**

### Random Number Generation

In [20]:
import numpy as np

np.random.rand(2, 3)

array([[0.59681737, 0.25140431, 0.30898015],
       [0.93610941, 0.18626734, 0.64186131]])

In [24]:
np.random.randn(2, 3)

array([[-2.70535322, -1.02734619, -0.13286454],
       [ 0.28258854,  0.85687218,  0.09393504]])

In [25]:
np.random.randint(1, 10, size=(2, 3))

array([[4, 3, 9],
       [7, 8, 2]])

### Matrix Creation Routines

In [26]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
np.zeros_like(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## **Numpy Array Indexing & Slicing**

1. Accessing Elements in 1D Arrays

In [31]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


2. Accessing Elements in Multidimensional Arrays

In [32]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[1, 2])

6


In [34]:
import numpy as np

cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

print(cube[1, 1, 2])

15


3. Slicing Arrays

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])

[2 3 4]


In [36]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


4. Boolean Indexing

In [37]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])

[25 30]


In [38]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[(arr > 10) & (arr < 30)])

[15 20 25]


5. Fancy Indexing

In [39]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]

print(arr[indices])

[10 30 50]


6. Integer Array Indexing

In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[[0, 2, 4]])

[1 3 5]


7. Ellipsis (...) in Indexing

In [41]:
import numpy as np

cube = np.random.rand(4, 4, 4)

print(cube[..., 0])

[[0.99580123 0.43696515 0.9886157  0.17605599]
 [0.41079138 0.93867202 0.55524287 0.52162665]
 [0.89272914 0.60043841 0.85613336 0.78308075]
 [0.04542434 0.61123145 0.87732786 0.54202868]]


8. Using np.newaxis to Add New Dimensions

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[:, np.newaxis])

[[1]
 [2]
 [3]
 [4]
 [5]]


9. Modifying Array Elements

In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[1:3] = 99

print(arr)

[ 1 99 99  4  5]


### In 2D Array

In [46]:
import numpy as np

arr = np.array([[10,20,30], [40,5,66], [70,88,94]])
print("Array:\n", arr)

res = arr[[0,2]]
print("Accessed rows:\n", res)

Array:
 [[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed rows:
 [[10 20 30]
 [70 88 94]]


In [47]:
import numpy as np

arr = np.array([[101,20,3,10], [40,5,66,7], [70,88,94,141]])
print("Array:\n", arr)

res = arr[1]
print("Accessed rows:\n", res)

Array:
 [[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88  94 141]]
Accessed rows:
 [40  5 66  7]


In [48]:
import numpy as np

arr = np.array([[12, 15, 18],
                [21, 24, 27],
                [30, 33, 36]])
print("Array:\n", arr)

res = arr[:2, :2]
print("Accessed subarray:\n", res)

Array:
 [[12 15 18]
 [21 24 27]
 [30 33 36]]
Accessed subarray:
 [[12 15]
 [21 24]]


### In 3D Arrays

In [49]:
import numpy as np

arr = np.array([[[10,25,70],
                 [15,30,80],
                 [20,35,90]],
                 [[11,26,71],
                 [16,31,81],
                 [21,36,91]]])
print("Array:\n", arr)

res = arr[:,[1]]
print("Accessed rows:\n", res)

Array:
 [[[10 25 70]
  [15 30 80]
  [20 35 90]]

 [[11 26 71]
  [16 31 81]
  [21 36 91]]]
Accessed rows:
 [[[15 30 80]]

 [[16 31 81]]]


In [50]:
import numpy as np

arr = np.array([[[10,25,70],[15,30,80],[20,35,90]],
                 [[11,26,71],[16,31,81],[21,36,91]],
                 [[12,27,72],[17,32,82],[22,37,92]]])
print("Array:\n", arr)

res = arr[:,[0,2]]
print("Accessed rows:\n", res)

Array:
 [[[10 25 70]
  [15 30 80]
  [20 35 90]]

 [[11 26 71]
  [16 31 81]
  [21 36 91]]

 [[12 27 72]
  [17 32 82]
  [22 37 92]]]
Accessed rows:
 [[[10 25 70]
  [20 35 90]]

 [[11 26 71]
  [21 36 91]]

 [[12 27 72]
  [22 37 92]]]


In [51]:
import numpy as np

arr = np.array([
    [[5,10,15], [20,25,30], [35,40,45]],
    [[20,25,30], [35,40,45], [50,55,60]],
    [[35,40,45], [50,55,60], [65,70,75]]
])
print("Array:\n", arr)

res = arr[:, :2, :2]
print("Accessed Elements:\n", res)

Array:
 [[[ 5 10 15]
  [20 25 30]
  [35 40 45]]

 [[20 25 30]
  [35 40 45]
  [50 55 60]]

 [[35 40 45]
  [50 55 60]
  [65 70 75]]]
Accessed Elements:
 [[[ 5 10]
  [20 25]]

 [[20 25]
  [35 40]]

 [[35 40]
  [50 55]]]


## **Reshaping & Resizing Arrays**

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3)

print(r)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
r = a.reshape(2, 2, 2)

print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)

print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))

print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr.resize((2, 2))

print(arr)

[[1 2]
 [3 4]]


## **Stacking & Splitting Arrays**

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=0)

print(res)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))
print(np.stack((a, b), axis=-1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [21]:
import numpy as np

x = np.array([[1, 2, 3],
             [4, 5, 6]])

y = np.array([[7, 8, 9],
             [10, 11, 12]])

print(np.stack((x, y), axis=0))
print("---------------------------------")
print(np.stack((x, y), axis=1))
print("---------------------------------")
print(np.stack((x, y), axis=-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------------------------
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
---------------------------------
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [24]:
import numpy as np

m = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

n = np.array([[[10, 20], [30, 40]],
              [[50, 60], [70, 80]]])

print(np.stack((m, n), axis=0))
print("---------------------------------")
print(np.stack((m, n), axis=1))
print("---------------------------------")
print(np.stack((m, n), axis=2))
print("---------------------------------")
print(np.stack((m, n), axis=3))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
---------------------------------
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
---------------------------------
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
---------------------------------
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


## **NumPy Array Broadcasting**

In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10

print(a + x)

[[11 12 13]
 [14 15 16]]


### Working of Broadcasting in NumPy

1. Broadcasting a scalar to a 1D Array

In [2]:
import numpy as np

arr = np.array([1, 2, 3])
res = arr + 1

print(res)

[2 3 4]


2. Broadcasting a 1D Array to a 2D Array

In [4]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b

print(res)

[[ 3  7 11]
 [ 9 13 17]]


3. Broadcasting in Conditional Operations

In [5]:
import numpy as np

a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(['Adult', 'Minor'])
res = np.where(a >= 18, b[0], b[1])

print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


4. Using Broadcasting for Matrix Multiplication

In [7]:
import numpy as np

m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])
res = m + v

print(res)

[[11 22]
 [13 24]]


5. Scaling Data with Broadcasting

In [8]:
import numpy as np

fd = np.array([[0.8, 2.9, 3.9],
               [52.4, 23.6, 36.5],
               [12.5, 45.6, 78.9],
               [9.1, 15.2, 25.3]])
cpg = np.array([9, 4, 4])
res = fd * cpg

print(res)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [112.5 182.4 315.6]
 [ 81.9  60.8 101.2]]


6. Adjusting Temperature Data Across Multiple Locations

In [9]:
import numpy as np

temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])
corr = np.array([1.5, -0.5, 2.0])
res = temp + corr[:, None]

print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


7. Normalizing Image Data

In [10]:
import numpy as np

img = np.array([ [100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120] ])
m = img.mean(axis=0)
s = img.std(axis=0)
res = (img - m) / s

print(res)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


8. Centering Data in Machine Learning

In [11]:
import numpy as np

data = np.array([ [10, 20],
                  [15, 25],
                  [20, 30] ])
m = data.mean(axis=0)
res = data - m

print(res)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
